Move sign and pub code to function
fix typo

Test remove files

fix lint

Fix non-release location

get location

Added comment

fix indent

fix indent again

fix path to repo

Call remove files from build sign release

add version print pester test

set expected and actual version

fix expected

Add more tests.

update tests

test -notmatch

fix version test

Remove dead code

Add TODO

Remove dead code

Add TODO

Fix unit test path

See location

Only list files

Adjust unit test to temp location

fix bug

fix path to git

use dummy folder

fix typo

redo pathing

Remove duplicate ModuleName "Microsoft.Graph.Beta.Applications" from RequiredVersions.ps1 (#1590)

* remove duplicate instance of 'Microsoft.Graph.Beta.Applications'

* inline with other graph modules

Ignore coexistence domain for the DMARC controls (#1563)

* Ignore coexistence domain

* Update copy/pasted comment

Update README.md with relative rather than absolute URL (#1576)

Update manifest copyright to include 2025 (#1603)

Test the output of ScubaGear's basic commands (#1538)

* add dispatch

* add push for testing

temp replace secrets

fix key vault

write the info

set specific info

add error

fix name

fix errors

Correct newline

Fix newline

continue to next line

Another newline fix

another output

remove whitespace

Clean up, should pass

fix variable name

check version

Add intentional name error

add exit 1

fix exit code

Fix one error.

get the module version

use actual version

add comments to find version problem

comments for version

add comment

Restore comments and version

use write-debug

use write-debug

switch to warning

try black magic

try black magic

Set correct version number

check initiliaze output

clarify output

Fix typo

Trivial change

Remove comment from output

Add outputs for initialize.

removed write-host

process the output

replace Python w PowerShell.

Put output up to Pester tests

Update outputs

fix global var name

Fix output var in Pester

test autotrust

lint

add key value tests

adjust pester test

remove dir output

Comment dir

remove dir

Continue hunt for dir

lint

find hidden output

improve writes

use value

more debugging comments

add comments

Lint

comment

comment

comment

clear function results

undo comments

fix typo

differentiate string from other types

list all output types

test for desired strings

lint

separate it sections

use global vars correctly

use global vars everywhere

move tests

Fix loop error

Tweak outputs

trim the string

remove testing code

Clean up calling secrets

Remove old comment

removed debugging statement

Remove debugging

Remove unused comments

fix opa version

fix write-warning

test write-verbose

Removed verbose

Removed return

fix extra braces

use env variable

Fixed comments and parameters

read description from manifest

Cleaned up debugging statements

* cleanup and remove debugging

* Add review edits

* add comments

* create $global:SetupTimeThreshold

Convert issue templates in markdown to GitHub's issue forms (#1562)

* revise issue form templates

* fix linter

* Update 1-newidea.yaml

* Update 1-newidea.yaml

* Update 2-bugreport.yaml

* add scubagear version

* add Initialize-SCuBA textarea (optional)

* add M365 environment/license input, switch ps version to dropdown

* add optional field for iniitialize-scuba

* appease linter

* make acceptance criteria required field

diff --git a/.github/workflows/publish_private_package.yaml b/.github/workflows/publish_private_package.yaml
--- a/.github/workflows/publish_private_package.yaml
+++ b/.github/workflows/publish_private_package.yaml
@@ -1,4 +1,5 @@
 # Purpose: Publishes ScubaGear to a private repo and caches ScubaGear modules and OPA for reuse.
+# Note: To test this workflow, run the functional tests.
 
 name: Publish Private Package
 
@@ -56,6 +57,8 @@ jobs:
           KEY_VAULT_INFO: ${{ secrets.KeyVaultInfo }}
         # Do not attempt to access the Key Vault if logging into Azure failed.
         if: ${{ success() }}
+        # Do not attempt to access the Key Vault if logging into Azure failed.
+        if: ${{ success() }}
         run: |
           $KeyVaultInfo = ${env:KEY_VAULT_INFO} | ConvertFrom-Json
           echo "KeyVaultUrl=$($KeyVaultInfo.KeyVault.URL)" >> $env:GITHUB_OUTPUT
@@ -67,23 +70,21 @@ jobs:
           New-PrivateGallery -GalleryName $env:GalleryName -Trusted
       - name: Sign and Publish Module
         id: sign-publish-module
+        id: sign-publish-module
         run: |
-            . repo/utils/workflow/Publish-ScubaGear.ps1
-            # Remove non-release files
-            Remove-Item -Recurse -Force repo -Include .git*
-            # Setup the parameters
-            $Parameters = @{
-              AzureKeyVaultUrl = '${{ steps.key-vault-info.outputs.KeyVaultUrl }}'
-              CertificateName = '${{ steps.key-vault-info.outputs.KeyVaultCertificateName }}'
-              ModuleSourcePath = 'repo/PowerShell/ScubaGear'
-              GalleryName = $env:GalleryName
-            }
-            # This publishes to a private gallery, from which we will pull in a future step.
-            # This step helps us verify that ScubaGear is in a state where it can be
-            # published to PSGallery.
-            $ModuleVersion = Publish-ScubaGearModule @Parameters
-            Write-Output "The module version is $ModuleVersion"
-            echo "ModuleVersion=$ModuleVersion" >> $env:GITHUB_OUTPUT
+          . repo/utils/workflow/Publish-ScubaGear.ps1
+          Remove-NonReleaseFiles -RootFolderName "repo"
+          # Setup the parameters
+          $Parameters = @{
+            AzureKeyVaultUrl = '${{ steps.key-vault-info.outputs.KeyVaultUrl }}'
+            CertificateName = '${{ steps.key-vault-info.outputs.KeyVaultCertificateName }}'
+            ModuleSourcePath = 'repo/PowerShell/ScubaGear'
+            GalleryName = $env:GalleryName
+          }
+          # This publishes to a private gallery, from which we will pull in a future step.
+          # This step helps us verify that ScubaGear is in a state where it can be
+          # published to PSGallery.
+          Publish-ScubaGearModule @Parameters
       - name: Test Module Publish
         run: |
           Get-Location
@@ -123,14 +124,43 @@ jobs:
             Write-Output "::error::The description of the published module should be $ExpectedDescription"
             exit 1
           }
+          # This step initializes SG and runs some checks to verify that it installed correctly.
+          $ExpectedName = 'ScubaGear'
+          # Read the description value from the manifest file (ScubaGear.psd1)
+          $ManifestFilePath = Join-Path -Path repo/PowerShell/ScubaGear -ChildPath 'ScubaGear.psd1' -Resolve
+          $Manifest = Import-PowerShellDataFile $ManifestFilePath
+          $ExpectedDescription = $Manifest.Description
+          # The -PassThru parameters allows us to read the output value from Install-Module
+          $InstallOutput = Install-Module -Name ScubaGear -Repository $env:GalleryName -SkipPublisherCheck -PassThru
+          # Check for the expected name.
+          if ($InstallOutput.Name -ne $ExpectedName) {
+            Write-Output "::error::The name of the published module should be $ExpectedName"
+            exit 1
+          }
+          # Because reasons, the description has a newline character.
+          # Strip all whitespace before comparing the descriptions.
+          $DescriptionFixed = $InstallOutput.Description -replace "\s", ""
+          $ExpectedFixed = $ExpectedDescription -replace "\s", ""
+          # Check for the expected description.
+          if ($DescriptionFixed -ne $ExpectedFixed) {
+            Write-Output "::error::The description of the published module should be $ExpectedDescription"
+            exit 1
+          }
           . repo/utils/workflow/Initialize-ScubaGearForTesting.ps1
           Initialize-ScubaGearForTesting
-          # Check for expected version.
-          $VersionOutput = Invoke-SCuBA -Version
-          $ExpectedVersion = "SCuBA Gear v${{ steps.sign-publish-module.outputs.ModuleVersion }}"
-          if ($VersionOutput -ne $ExpectedVersion) {
-            Write-Output "::error::The version of the published module should be $ExpectedVersion"
+          # What follows are 2 quick tests to verify that ScubaGear initialized correctly.
+          # Test #1 - Version works
+          $ManifestFilePath = Join-Path -Path "repo\PowerShell\ScubaGear" -ChildPath "ScubaGear.psd1"
+          $ExpectedVersion = (Import-PowerShellDataFile $ManifestFilePath).ModuleVersion
+          $ActualVersion = Invoke-SCuBA -Version
+          if ($ActualVersion -notmatch $ExpectedVersion) {
+            Write-Output "::error::The module version should contain with $ExpectedVersion"
             exit 1
+          }
+          # Test #2 - Path exists
+          $PathExists = Test-Path -Path "C:\Program Files\WindowsPowerShell\Modules\ScubaGear"
+          if ($PathExists -ne $true) {
+            Write-Output "::error::ScubaGear was not installed into the correct version."
           }
       - name: Install Selenium
         run: |
