add push for testing
temp replace secrets

fix key vault

write the info

set specific info

add error

fix name

fix errors

Correct newline

Fix newline

continue to next line

Another newline fix

another output

remove whitespace

Clean up, should pass

fix variable name

check version

Add intentional name error

add exit 1

fix exit code

Fix one error.

get the module version

use actual version

add comments to find version problem

comments for version

add comment

Restore comments and version

use write-debug

use write-debug

switch to warning

try black magic

try black magic

Set correct version number

check initiliaze output

clarify output

Fix typo

Trivial change

Remove comment from output

Add outputs for initialize.

removed write-host

process the output

replace Python w PowerShell.

Put output up to Pester tests

Update outputs

fix global var name

Fix output var in Pester

test autotrust

lint

add key value tests

adjust pester test

remove dir output

Comment dir

remove dir

Continue hunt for dir

lint

find hidden output

improve writes

use value

more debugging comments

add comments

Lint

comment

comment

comment

clear function results

undo comments

fix typo

differentiate string from other types

list all output types

test for desired strings

lint

separate it sections

use global vars correctly

use global vars everywhere

move tests

Fix loop error

Tweak outputs

trim the string

remove testing code

Clean up calling secrets

Remove old comment

removed debugging statement

Remove debugging

Remove unused comments

fix opa version

fix write-warning

test write-verbose

Removed verbose

Removed return

fix extra braces

use env variable

Fixed comments and parameters

read description from manifest

Cleaned up debugging statements

diff --git a/.github/workflows/publish_private_package.yaml b/.github/workflows/publish_private_package.yaml
--- a/.github/workflows/publish_private_package.yaml
+++ b/.github/workflows/publish_private_package.yaml
@@ -14,7 +14,6 @@ on:
         required: true
       KeyVaultInfo:
         required: true
-  workflow_dispatch:
 
 permissions:
   id-token: write
@@ -55,6 +54,8 @@ jobs:
         id: key-vault-info
         env:
           KEY_VAULT_INFO: ${{ secrets.KeyVaultInfo }}
+        # Do not attempt to access the Key Vault if logging into Azure failed.
+        if: ${{ success() }}
         run: |
           $KeyVaultInfo = ${env:KEY_VAULT_INFO} | ConvertFrom-Json
           echo "KeyVaultUrl=$($KeyVaultInfo.KeyVault.URL)" >> $env:GITHUB_OUTPUT
@@ -65,6 +66,7 @@ jobs:
           cd repo
           New-PrivateGallery -GalleryName $env:GalleryName -Trusted
       - name: Sign and Publish Module
+        id: sign-publish-module
         run: |
             . repo/utils/workflow/Publish-ScubaGear.ps1
             # Remove non-release files
@@ -79,7 +81,9 @@ jobs:
             # This publishes to a private gallery, from which we will pull in a future step.
             # This step helps us verify that ScubaGear is in a state where it can be
             # published to PSGallery.
-            Publish-ScubaGearModule @Parameters
+            $ModuleVersion = Publish-ScubaGearModule @Parameters
+            Write-Output "The module version is $ModuleVersion"
+            echo "ModuleVersion=$ModuleVersion" >> $env:GITHUB_OUTPUT
       - name: Test Module Publish
         run: |
           Get-Location
@@ -97,15 +101,42 @@ jobs:
           Invoke-Pester -Configuration $Config
       - name: Initialize ScubaGear
         run: |
-          Write-Output "Preparing to install..."
-          Install-Module -Name ScubaGear -Repository $env:GalleryName -SkipPublisherCheck
-          Write-Output "Finished installing..."
+          # Name and description are two of the expected output values that result from
+          # installing the module.  These checks are intended to help verify that the module
+          # installed correctly.
+          $ExpectedName = 'ScubaGear'
+          # Read the description value from the manifest file (ScubaGear.psd1)
+          $ManifestFilePath = Join-Path -Path repo/PowerShell/ScubaGear -ChildPath 'ScubaGear.psd1' -Resolve
+          $Manifest = Import-PowerShellDataFile $ManifestFilePath
+          $ExpectedDescription = $Manifest.Description
+          # The -PassThru paramaters allows us to read the output
+          # value from Install-Module
+          $InstallOutput = Install-Module -Name ScubaGear -Repository $env:GalleryName -SkipPublisherCheck -PassThru
+          # Check for the expected name.
+          if ($InstallOutput.Name -ne $ExpectedName) {
+            Write-Output "::error::The name of the published module should be $ExpectedName"
+            exit 1
+          }
+          # Because reasons, the description has a newline character.
+          # Strip all whitespace before comparing the descriptions.
+          $DescriptionFixed = $InstallOutput.Description -replace "\s", ""
+          $ExpectedFixed = $ExpectedDescription -replace "\s", ""
+          # Check for the expected description.
+          if ($DescriptionFixed -ne $ExpectedFixed) {
+            Write-Output "::error::The description of the published module should be $ExpectedDescription"
+            exit 1
+          }
           # Source the function
           . repo/utils/workflow/Initialize-ScubaGearForTesting.ps1
           Initialize-ScubaGearForTesting
-          # This is a manual test that simply writes the version to the console.
-          Invoke-SCuBA -Version
-          Test-Path -Path "C:\Program Files\WindowsPowerShell\Modules\ScubaGear"
+          # This is the expected output value that results from running the module.
+          # This check is intended to help verify that ScubaGear installed correctly.
+          $VersionOutput = Invoke-SCuBA -Version
+          $ExpectedVersion = "SCuBA Gear v${{ steps.sign-publish-module.outputs.ModuleVersion }}"
+          if ($VersionOutput -ne $ExpectedVersion) {
+            Write-Output "::error::The version of the published module should be $ExpectedVersion"
+            exit 1
+          }
       - name: Install Selenium
         run: |
           . repo/utils/workflow/Install-SeleniumForTesting.ps1
